### ISSUE TITLE
Auto hide

### ISSUE THREAD

**Issue by vorticalbox** [lee8oi/hexperience#6] opened 2017-01-28 15:09 UTC
Auto hide no longer works.

**Comment by lee8oi** [comment] 2017-01-28 19:38
Been a while since I played the game or worked on this script. But I'll see what I can do. Thanks for the report.

**Comment by lee8oi** [comment] 2017-01-31 18:58
New fixes in place that should resolve this issue.

**Comment by lee8oi** [comment] 2017-01-31 19:34
Reopening this issue until problem is confirmed to be resolved.

**Comment by lee8oi** [comment] 2017-02-01 02:24
Auto hideme is working for me. So I'm closing this issue for good now. If you have further problems open a new issue.

**Closed as completed by lee8oi** 2017-02-01 02:24 UTC
